/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlexContainer {
        "isAligned": string;
        "isCol": boolean;
        "isJustified": string;
        "isReverse": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RainbowBackground {
    }
    interface SnButton {
        "appearance": string;
        "text": string;
    }
    interface SnColorH1 {
        "start": string;
        "stop": string;
    }
    interface SnIcon {
        "appearance": string;
        "icon": string;
        "viewBox": string;
    }
    interface SnSocial {
    }
}
declare global {
    interface HTMLFlexContainerElement extends Components.FlexContainer, HTMLStencilElement {
    }
    var HTMLFlexContainerElement: {
        prototype: HTMLFlexContainerElement;
        new (): HTMLFlexContainerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRainbowBackgroundElement extends Components.RainbowBackground, HTMLStencilElement {
    }
    var HTMLRainbowBackgroundElement: {
        prototype: HTMLRainbowBackgroundElement;
        new (): HTMLRainbowBackgroundElement;
    };
    interface HTMLSnButtonElement extends Components.SnButton, HTMLStencilElement {
    }
    var HTMLSnButtonElement: {
        prototype: HTMLSnButtonElement;
        new (): HTMLSnButtonElement;
    };
    interface HTMLSnColorH1Element extends Components.SnColorH1, HTMLStencilElement {
    }
    var HTMLSnColorH1Element: {
        prototype: HTMLSnColorH1Element;
        new (): HTMLSnColorH1Element;
    };
    interface HTMLSnIconElement extends Components.SnIcon, HTMLStencilElement {
    }
    var HTMLSnIconElement: {
        prototype: HTMLSnIconElement;
        new (): HTMLSnIconElement;
    };
    interface HTMLSnSocialElement extends Components.SnSocial, HTMLStencilElement {
    }
    var HTMLSnSocialElement: {
        prototype: HTMLSnSocialElement;
        new (): HTMLSnSocialElement;
    };
    interface HTMLElementTagNameMap {
        "flex-container": HTMLFlexContainerElement;
        "my-component": HTMLMyComponentElement;
        "rainbow-background": HTMLRainbowBackgroundElement;
        "sn-button": HTMLSnButtonElement;
        "sn-color-h1": HTMLSnColorH1Element;
        "sn-icon": HTMLSnIconElement;
        "sn-social": HTMLSnSocialElement;
    }
}
declare namespace LocalJSX {
    interface FlexContainer {
        "isAligned"?: string;
        "isCol"?: boolean;
        "isJustified"?: string;
        "isReverse"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RainbowBackground {
    }
    interface SnButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface SnColorH1 {
        "start"?: string;
        "stop"?: string;
    }
    interface SnIcon {
        "appearance"?: string;
        "icon"?: string;
        "viewBox"?: string;
    }
    interface SnSocial {
    }
    interface IntrinsicElements {
        "flex-container": FlexContainer;
        "my-component": MyComponent;
        "rainbow-background": RainbowBackground;
        "sn-button": SnButton;
        "sn-color-h1": SnColorH1;
        "sn-icon": SnIcon;
        "sn-social": SnSocial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flex-container": LocalJSX.FlexContainer & JSXBase.HTMLAttributes<HTMLFlexContainerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "rainbow-background": LocalJSX.RainbowBackground & JSXBase.HTMLAttributes<HTMLRainbowBackgroundElement>;
            "sn-button": LocalJSX.SnButton & JSXBase.HTMLAttributes<HTMLSnButtonElement>;
            "sn-color-h1": LocalJSX.SnColorH1 & JSXBase.HTMLAttributes<HTMLSnColorH1Element>;
            "sn-icon": LocalJSX.SnIcon & JSXBase.HTMLAttributes<HTMLSnIconElement>;
            "sn-social": LocalJSX.SnSocial & JSXBase.HTMLAttributes<HTMLSnSocialElement>;
        }
    }
}
